package edu.harvard.hms.dbmi.avillach.gateway.docs;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import edu.harvard.hms.dbmi.avillach.commons.openapi.OpenApiExport;

/**
 * The rewrite contract, tested against the classpath copy the build makes and the committed source it came from: the served document says
 * exactly where its API lives publicly, and is otherwise the committed document untouched.
 */
class OpenApiDocumentsTest {

    private final ObjectMapper json = new ObjectMapper();
    private final OpenApiDocuments documents = new OpenApiDocuments(json);

    @ParameterizedTest
    @EnumSource(ContractDocument.class)
    void everyContractDocumentIsOnTheClasspathAndServable(ContractDocument document) {
        assertThat(documents.document(document.fileName()))
            .as("the copy-contract-documents build step must put %s on the classpath", document.fileName()).isPresent();
    }

    /**
     * The regression that matters most: the committed documents are build artifacts of record, regenerated byte-for-byte by each service's
     * {@code OpenApiExportTest}. Serving them may substitute the placeholder {@code servers} and NOTHING else -- any other divergence would
     * mean the console is describing an API the contract does not.
     */
    @ParameterizedTest
    @EnumSource(ContractDocument.class)
    void servingChangesNothingButTheServersArray(ContractDocument document) throws IOException {
        JsonNode served = json.readTree(documents.document(document.fileName()).orElseThrow());
        JsonNode committed = json.readTree(committedDocument(document));

        assertThat(withoutServers(served)).isEqualTo(withoutServers(committed));
        assertThat(committed.path("servers").path(0).path("url").asText()).as("the committed placeholder the rewrite replaces")
            .isEqualTo("http://localhost");
    }

    @ParameterizedTest
    @EnumSource(value = ContractDocument.class, names = "HPDS", mode = EnumSource.Mode.EXCLUDE)
    void aRoutableDocumentDeclaresItsPublicIngressAsTheOnlyServer(ContractDocument document) throws IOException {
        JsonNode servers = json.readTree(documents.document(document.fileName()).orElseThrow()).path("servers");

        assertThat(servers).hasSize(1);
        assertThat(servers.path(0).path("url").asText()).isEqualTo(document.publicServer().orElseThrow());
        assertThat(servers.path(0).path("description").asText()).isEqualTo(ContractDocument.SERVER_DESCRIPTION);
    }

    /**
     * {@code pic-sure-hpds} has no httpd rule and no gateway route -- the query service is its only client. An empty {@code servers} is the
     * honest statement of that: the document is published to be read, and offers the viewer no URL to call.
     */
    @Test
    void theUnroutableDocumentDeclaresNoServerAtAll() throws IOException {
        JsonNode servers = json.readTree(documents.document(ContractDocument.HPDS.fileName()).orElseThrow()).path("servers");

        assertThat(servers.isArray()).isTrue();
        assertThat(servers).isEmpty();
        assertThat(ContractDocument.HPDS.publiclyRoutable()).isFalse();
    }

    @Test
    void anUnknownDocumentNameResolvesToNothing() {
        assertThat(documents.document("../../application.yml")).isEmpty();
        assertThat(documents.document("pic-sure-hpds.openapi.json.bak")).isEmpty();
        assertThat(documents.document("")).isEmpty();
    }

    @Test
    void theIndexListsAllSixWithTheirPublicServers() throws IOException {
        JsonNode index = json.readTree(documents.index()).path("documents");

        assertThat(index).hasSize(ContractDocument.values().length);
        for (int i = 0; i < ContractDocument.values().length; i++) {
            ContractDocument document = ContractDocument.values()[i];
            JsonNode entry = index.get(i);
            assertThat(entry.path("name").asText()).isEqualTo(document.artifactId());
            assertThat(entry.path("file").asText()).isEqualTo(document.fileName());
            assertThat(entry.path("title").asText()).isEqualTo(document.title());
            assertThat(entry.path("publiclyRoutable").asBoolean()).isEqualTo(document.publiclyRoutable());
            assertThat(entry.has("server")).isEqualTo(document.publiclyRoutable());
        }
    }

    /**
     * The enum's file names must be the actual committed file names -- the check that catches a document renamed or removed under the
     * gateway, which would otherwise only surface as a startup failure in a deployed environment.
     */
    @Test
    void everyEnumEntryNamesACommittedDocument() {
        for (ContractDocument document : ContractDocument.all()) {
            assertThat(committedPath(document)).as("committed source for %s", document).exists();
        }
    }

    private static JsonNode withoutServers(JsonNode document) {
        ObjectNode copy = document.deepCopy();
        copy.remove("servers");
        return copy;
    }

    private static String committedDocument(ContractDocument document) throws IOException {
        return Files.readString(committedPath(document), StandardCharsets.UTF_8);
    }

    private static Path committedPath(ContractDocument document) {
        return OpenApiExport.repoRoot().resolve("docs").resolve("api").resolve(document.fileName());
    }
}
