package edu.harvard.hms.dbmi.avillach.gateway.docs;

import java.util.List;
import java.util.Optional;

/**
 * The six committed contract documents ({@code docs/api/*.openapi.json}) the gateway serves, each paired with the PUBLIC path prefix a
 * browser must call to reach that service.
 *
 * <p>This enum is the single source of truth for the docs console: the {@code /openapi} index, the served {@code servers} rewrite, and the
 * viewer's service picker are all derived from it, so a document can never appear in one and not the others.
 *
 * <p><b>Why a rewrite is needed at all.</b> The committed documents carry springdoc's placeholder server, {@code http://localhost}. They
 * are build artifacts of record, regenerated byte-for-byte by each service's {@code OpenApiExportTest}, so the gateway must NEVER edit them
 * on disk -- it rewrites {@code servers} on the way out, and nothing else.
 *
 * <p><b>How each prefix is derived.</b> Public ingress is Apache httpd, which proxies {@code /picsure/(.*)} to the gateway with the
 * {@code /picsure} segment STRIPPED, and {@code /psama/(.*)} straight to the auth service's own {@code /auth} context path, bypassing the
 * gateway entirely. So for a gateway-served document the public prefix is {@code /picsure} plus whatever the gateway's own route adds back
 * on top of the paths the document declares.
 *
 * <p>{@code /hpds/**} and {@code /operations/**} route VERBATIM (no {@code StripPrefix}). The query-service documents its paths WITH the
 * {@code /hpds} prefix already, so {@code /picsure} alone completes them; operations-service serves under a {@code /operations} context
 * path that springdoc omits from the document, so its prefix must add {@code /operations} back.
 *
 * <p>{@code /dictionary/**} and {@code /visualization/**} route with {@code StripPrefix=1} to services that serve their APIs at root, so
 * their documented (post-strip) paths need the routed segment added back.
 *
 * <p>PSAMA's document is written against the {@code /auth} context path that httpd's {@code /psama} rule substitutes one-for-one -- hence a
 * bare {@code /psama}, and no {@code /picsure} at all.
 *
 * <p><b>The one exception.</b> {@code pic-sure-hpds} has no ingress at all: no httpd rule and no gateway route reaches it, by design (the
 * query-service is HPDS's only client). It is served here to be READ, never called, so it declares no server -- see
 * {@link #publiclyRoutable()}.
 */
public enum ContractDocument {

    /** Query service: documents its own {@code /hpds/...} paths, routed verbatim, so {@code /picsure} completes them. */
    QUERY_SERVICE("pic-sure-hpds-query-service", "Query Service (HPDS v3)", "/picsure"),

    /** Operations service: {@code server.servlet.context-path=/operations}, which springdoc leaves out of the document. */
    OPERATIONS("pic-sure-operations-service", "Operations Service", "/picsure/operations"),

    /** Dictionary: serves at root behind a {@code StripPrefix=1} {@code /dictionary} route. */
    DICTIONARY("picsure-dictionary", "Dictionary", "/picsure/dictionary"),

    /** Visualization: serves at root behind a {@code StripPrefix=1} {@code /visualization} route. */
    VISUALIZATION("pic-sure-visualization-service", "Visualization", "/picsure/visualization"),

    /** PSAMA: httpd proxies {@code /psama/**} straight to its {@code /auth} context path, bypassing the gateway. */
    AUTH("pic-sure-auth-services", "Auth (PSAMA)", "/psama"),

    /** HPDS: no public ingress by design; readable here, not callable. Always last so the picker lists it last. */
    HPDS("pic-sure-hpds", "HPDS (internal — not publicly routable)", null);

    /** What the served {@code servers[0].description} says, so a reader of the raw document knows the URL is not the generator's. */
    static final String SERVER_DESCRIPTION = "PIC-SURE public ingress";

    private static final String SUFFIX = ".openapi.json";

    private final String artifactId;
    private final String title;
    private final String publicServer;

    ContractDocument(String artifactId, String title, String publicServer) {
        this.artifactId = artifactId;
        this.title = title;
        this.publicServer = publicServer;
    }

    /** The generating module's artifactId -- also the document's stem, since the exporters name files after it. */
    public String artifactId() {
        return artifactId;
    }

    /** The document's file name, both on the classpath and as the {@code /openapi/{document}} path variable. */
    public String fileName() {
        return artifactId + SUFFIX;
    }

    /** Human label for the viewer's picker and the {@code /openapi} index. */
    public String title() {
        return title;
    }

    /** The public path prefix a browser prepends to this document's paths; empty for a document with no ingress. */
    public Optional<String> publicServer() {
        return Optional.ofNullable(publicServer);
    }

    /** False for {@code pic-sure-hpds}: readable, but no request from a browser can reach it. */
    public boolean publiclyRoutable() {
        return publicServer != null;
    }

    /** All six, in declaration order -- which is the order the index and the viewer's picker present them. */
    public static List<ContractDocument> all() {
        return List.of(values());
    }
}
