DROP TABLE IF EXISTS `query_status`;

CREATE TABLE `query_status` (
    QUERY BINARY(16) NOT NULL,
    GENOMIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'NotStarted',
    PHENOTYPIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'NotStarted',
    PRIMARY KEY (`QUERY`)
);

INSERT INTO `query_status` (QUERY, GENOMIC_STATUS, PHENOTYPIC_STATUS)
    VALUES (unhex('33613336393437612D383233312D3131'), 'Complete', 'Error');