name: pic-sure-hpds-etl-csv-loader
services:
  csv-loader:
    image: pic-sure-hpds-etl:local
    build:
      context: ../..
      dockerfile: docker/pic-sure-hpds-etl/Dockerfile
    environment:
      - HEAPSIZE=4096
      - LOADER_NAME=CSVLoader
    volumes:
      - ./hpds:/opt/local/phenocube
      - ./hpds:/opt/local/hpds
