name: pic-sure-hpds-etl-variant-loader
services:
  variant-loader:
    image: pic-sure-hpds-etl:local
    build:
      context: ../..
      dockerfile: docker/pic-sure-hpds-etl/Dockerfile
    environment:
      - HEAPSIZE=26000
      - LOADER_NAME=VCFLocalLoader
    volumes:
      - ./hpds:/opt/local/hpds
      - ./vcfLoad:/opt/local/hpds/vcfInput
      - ./hpds/all:/opt/local/hpds/vcfOutput
