CREATE TABLE IF NOT EXISTS `query_status` (
    QUERY BINARY(16) NOT NULL,
    GENOMIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    PHENOTYPIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    APPROVED DATETIME,
    SITE VARCHAR(64) NOT NULL DEFAULT '',
    PRIMARY KEY (`QUERY`)
);
