package edu.harvard.hms.dbmi.avillach.auth;

import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.request.RequestPostProcessor;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import edu.harvard.hms.dbmi.avillach.auth.entity.AccessRule;
import edu.harvard.hms.dbmi.avillach.auth.entity.Application;
import edu.harvard.hms.dbmi.avillach.auth.entity.Privilege;
import edu.harvard.hms.dbmi.avillach.auth.entity.Role;
import edu.harvard.hms.dbmi.avillach.auth.entity.User;
import edu.harvard.hms.dbmi.avillach.auth.repository.AccessRuleRepository;
import edu.harvard.hms.dbmi.avillach.auth.repository.ApplicationRepository;
import edu.harvard.hms.dbmi.avillach.auth.repository.PrivilegeRepository;
import edu.harvard.hms.dbmi.avillach.auth.repository.RoleRepository;
import edu.harvard.hms.dbmi.avillach.auth.repository.UserRepository;
import edu.harvard.hms.dbmi.avillach.auth.service.impl.SessionService;
import edu.harvard.hms.dbmi.avillach.auth.utils.AuthNaming;
import edu.harvard.hms.dbmi.avillach.auth.utils.JWTUtil;

/**
 * Reproduces every non-2xx response the OpenAPI document declares for PSAMA's controllers through a real request: the servlet context path,
 * the security filter chain with {@code JWTFilter}, method security, the controllers, the services, Hibernate, and
 * {@code GlobalExceptionHandler}. Only the outbound FENCE call is stubbed, by a local HTTP server.
 *
 * <p> The schema is H2 in MySQL mode, generated by Hibernate from the entity mappings. Those mappings declare every foreign key the 409
 * cases depend on ({@code user_role}, {@code role_privilege}, {@code accessRule_privilege}, {@code accessRule_gate},
 * {@code privilege.application_id}, {@code user.connectionId}, {@code userMetadataMapping.connectionId}), matching the constraints in the
 * MySQL migrations, so each 409 comes from a real integrity violation. </p>
 *
 * <p> Requests authenticate the way production callers do: a JWT signed with the configured client secret whose subject is a stored, active
 * user, bound by its {@code sid} claim to a live session. {@code JWTFilter} rejects a token whose session is missing or ended, then loads
 * that user and grants the names of the privileges on the user's roles as authorities, which is what {@code @RolesAllowed} checks. </p>
 */
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.MOCK,
    properties = {"spring.datasource.url=jdbc:h2:mem:psama-documented-responses;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER,VALUE,KEY",
        "spring.datasource.driver-class-name=org.h2.Driver", "spring.datasource.username=sa", "spring.datasource.password=",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect", "spring.jpa.hibernate.ddl-auto=create-drop",
        "APPLICATION_CLIENT_SECRET=documented-responses-test-secret-at-least-32-bytes", "management.endpoints.web.exposure.include=none",
        "application.tos.enabled=false", "fence.idp.provider.is.enabled=true", "fence.client.id=test-client",
        "fence.client.secret=test-secret"}
)
@AutoConfigureMockMvc
class DocumentedErrorResponsesTest {

    static final String CONTEXT_PATH = "/auth";
    static final String SUPER_ADMIN_SUBJECT = "test|documented-responses-super-admin";
    static final String REJECTED_FENCE_CODE = "expiredcode123";

    static final HttpServer FENCE = startFence();

    @Autowired
    MockMvc mockMvc;

    @Autowired
    JWTUtil jwtUtil;

    @Autowired
    UserRepository userRepository;

    @Autowired
    RoleRepository roleRepository;

    @Autowired
    PrivilegeRepository privilegeRepository;

    @Autowired
    AccessRuleRepository accessRuleRepository;

    @Autowired
    ApplicationRepository applicationRepository;

    @Autowired
    SessionService sessionService;

    String superAdminToken;

    /** Stands in for FENCE's OAuth token endpoint, which answers an unusable authorization code with 400 {@code invalid_grant}. */
    static HttpServer startFence() {
        try {
            HttpServer server = HttpServer.create(new InetSocketAddress("localhost", 0), 0);
            server.createContext("/user/oauth2/token", exchange -> respond(exchange, 400, "{\"error\":\"invalid_grant\"}"));
            server.start();
            return server;
        } catch (IOException e) {
            throw new IllegalStateException("Cannot start the FENCE stub", e);
        }
    }

    static void respond(HttpExchange exchange, int status, String body) throws IOException {
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().add(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE);
        exchange.sendResponseHeaders(status, bytes.length);
        try (OutputStream out = exchange.getResponseBody()) {
            out.write(bytes);
        }
    }

    @AfterAll
    static void stopFence() {
        FENCE.stop(0);
    }

    @DynamicPropertySource
    static void fenceProps(DynamicPropertyRegistry registry) {
        registry.add("fence.idp.provider.uri", () -> "http://localhost:" + FENCE.getAddress().getPort());
    }

    @BeforeEach
    void signInSuperAdmin() {
        if (userRepository.findBySubject(SUPER_ADMIN_SUBJECT) == null) {
            Privilege superAdmin = privilegeRepository.findByName(AuthNaming.AuthRoleNaming.SUPER_ADMIN);
            if (superAdmin == null) {
                superAdmin = privilege(AuthNaming.AuthRoleNaming.SUPER_ADMIN);
            }
            userWithRole(SUPER_ADMIN_SUBJECT, role("SUPER_ADMIN_ROLE", superAdmin));
        }
        String sessionId = UUID.randomUUID().toString();
        sessionService.startSession(SUPER_ADMIN_SUBJECT, sessionId);
        superAdminToken = jwtUtil.createJwtToken(null, null, new HashMap<>(Map.of("sid", sessionId)), SUPER_ADMIN_SUBJECT, 60_000L);
    }

    @Test
    void unknownAccessRuleIs404() throws Exception {
        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/accessRule/{id}", UUID.randomUUID())).andExpect(status().isNotFound())
            .andExpect(jsonPath("$.message").value("AccessRule not found"));
    }

    @Test
    void creatingNoAccessRulesIs400() throws Exception {
        mockMvc.perform(asSuperAdmin(HttpMethod.POST, "/accessRule").contentType(MediaType.APPLICATION_JSON).content("[]"))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("No access rules added"));
    }

    @Test
    void deletingAnAccessRuleAPrivilegeStillHoldsIs409() throws Exception {
        AccessRule rule = accessRule("AR_HELD_" + UUID.randomUUID());
        Privilege holder = privilege("PRIV_HOLDING_RULE_" + UUID.randomUUID());
        holder.setAccessRules(new HashSet<>(Set.of(rule)));
        privilegeRepository.save(holder);

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/accessRule/{id}", rule.getUuid())).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void deletingAnAccessRuleAnotherRuleUsesAsAGateIs409() throws Exception {
        AccessRule gate = accessRule("AR_GATE_" + UUID.randomUUID());
        AccessRule gated = new AccessRule();
        gated.setName("AR_GATED_" + UUID.randomUUID());
        gated.setType(AccessRule.TypeNaming.ALL_EQUALS);
        gated.setGates(new HashSet<>(Set.of(gate)));
        accessRuleRepository.save(gated);

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/accessRule/{id}", gate.getUuid())).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void unknownApplicationIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/application/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(content().string("Application is not found by given Application ID: " + unknown));
    }

    @Test
    void refreshingTheTokenOfAnUnknownApplicationIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/application/refreshToken/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.content").value("Cannot find application by the given applicationId: " + unknown));
    }

    @Test
    void deletingAnUnknownApplicationIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/application/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(content().string("Cannot find application by the given applicationId: " + unknown));
    }

    @Test
    void deletingAnApplicationWhosePrivilegeIsStillOnARoleIs409() throws Exception {
        Application application = new Application();
        application.setName("APP_" + UUID.randomUUID());
        application = applicationRepository.save(application);
        Privilege privilege = new Privilege();
        privilege.setName("PRIV_OF_APP_" + UUID.randomUUID());
        privilege.setApplication(application);
        privilege = privilegeRepository.save(privilege);
        role("ROLE_HOLDING_APP_PRIVILEGE", privilege);

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/application/{id}", application.getUuid())).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void unknownRoleIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/role/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(content().string("Role is not found by given role ID: " + unknown));
    }

    @Test
    void deletingAnUnknownRoleIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/role/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(content().string("Role not found - uuid: " + unknown));
    }

    @Test
    void deletingARoleStillAssignedToAUserIs409() throws Exception {
        Role assigned = role("ROLE_ASSIGNED", privilege("PRIV_OF_ASSIGNED_ROLE_" + UUID.randomUUID()));
        userWithRole("test|holder-" + UUID.randomUUID(), assigned);

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/role/{id}", assigned.getUuid())).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void unknownPrivilegeIs400() throws Exception {
        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/privilege/{id}", UUID.randomUUID())).andExpect(status().isBadRequest())
            .andExpect(content().string("Privilege not found"));
    }

    @Test
    void deletingAPrivilegeARoleStillHoldsIs409() throws Exception {
        Privilege held = privilege("PRIV_HELD_" + UUID.randomUUID());
        role("ROLE_HOLDING_PRIVILEGE", held);

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/privilege/{id}", held.getUuid())).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void unknownUserIs400() throws Exception {
        UUID unknown = UUID.randomUUID();

        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/user/{id}", unknown)).andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.content").value("Cannot find user by input UUID: " + unknown));
    }

    @Test
    void userIdThatIsNotAUuidIs400() throws Exception {
        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/user/{id}", "not-a-uuid")).andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.message").value("Invalid request"));
    }

    @Test
    void unknownConnectionIs400() throws Exception {
        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/connection/{id}", "no-such-connection")).andExpect(status().isBadRequest())
            .andExpect(content().string("Connection with id no-such-connection not found"));
    }

    @Test
    void deletingAConnectionItsMetadataMappingStillReferencesIs409() throws Exception {
        String connectionId = "conn-" + UUID.randomUUID();
        String connections = "[{\"id\":\"" + connectionId + "\",\"label\":\"Test\",\"subPrefix\":\"test|\",\"requiredFields\":\"[]\"}]";
        mockMvc.perform(asSuperAdmin(HttpMethod.POST, "/connection").contentType(MediaType.APPLICATION_JSON).content(connections))
            .andExpect(status().isOk());

        mockMvc.perform(asSuperAdmin(HttpMethod.DELETE, "/connection/{id}", connectionId)).andExpect(status().isConflict())
            .andExpect(jsonPath("$.message").value("Cannot delete this resource as it's referenced by other entities in the system"));
    }

    @Test
    void unknownIdentityProviderIs400() throws Exception {
        mockMvc
            .perform(anonymous(HttpMethod.POST, "/authentication/{idp}", "nosuchidp").contentType(MediaType.APPLICATION_JSON).content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.content").value("No authentication service found for provider: nosuchidp"));
    }

    @Test
    void codeTheIdentityProviderRejectsIs401() throws Exception {
        mockMvc.perform(
            anonymous(HttpMethod.POST, "/authentication/{idp}", "fence").contentType(MediaType.APPLICATION_JSON)
                .content("{\"code\":\"" + REJECTED_FENCE_CODE + "\"}")
        ).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.message").value("Authorization failed"));
    }

    @Test
    void malformedIdentityProviderCodeIs401() throws Exception {
        mockMvc.perform(
            anonymous(HttpMethod.POST, "/authentication/{idp}", "fence").contentType(MediaType.APPLICATION_JSON)
                .content("{\"code\":\"not/alphanumeric\"}")
        ).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.content").value("The fence code is not alphanumeric"));
    }

    @Test
    void refreshingATokenWhoseSessionEndedIs401() throws Exception {
        sessionService.endSession(SUPER_ADMIN_SUBJECT);

        mockMvc.perform(asSuperAdmin(HttpMethod.GET, "/token/refresh")).andExpect(status().isUnauthorized())
            .andExpect(status().reason("Your session has expired. Please log in again."));
    }

    /**
     * The cache inspection controller only exists when {@code app.cache.inspect.enabled} is true, so its cases run in a context of its own
     * with a separate in-memory database. PSAMA uses Spring Boot's simple cache manager without {@code spring.cache.cache-names}, which
     * creates any cache it is asked for, so the controller's "cache not found" branch cannot run and the endpoint declares no 400. Both
     * reads admit only {@code SUPER_ADMIN}, so requests carry a test user holding a single authority rather than a JWT.
     */
    @Nested
    @TestPropertySource(
        properties = {"app.cache.inspect.enabled=true",
            "spring.datasource.url=jdbc:h2:mem:psama-cache-inspection;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER,VALUE,KEY"}
    )
    class CacheInspection {

        @Autowired
        MockMvc cacheInspectionMockMvc;

        @Test
        void unknownCacheNameReturnsANewEmptyCache() throws Exception {
            cacheInspectionMockMvc
                .perform(anonymous(HttpMethod.GET, "/cache/{name}", "nope").with(holding(AuthNaming.AuthRoleNaming.SUPER_ADMIN)))
                .andExpect(status().isOk()).andExpect(content().json("{}"));
        }

        @Test
        void superAdminCanListCacheNames() throws Exception {
            cacheInspectionMockMvc.perform(anonymous(HttpMethod.GET, "/cache").with(holding(AuthNaming.AuthRoleNaming.SUPER_ADMIN)))
                .andExpect(status().isOk());
        }

        @Test
        void superAdminCanDumpTheSessionsCache() throws Exception {
            cacheInspectionMockMvc
                .perform(anonymous(HttpMethod.GET, "/cache/{name}", "sessions").with(holding(AuthNaming.AuthRoleNaming.SUPER_ADMIN)))
                .andExpect(status().isOk());
        }

        @Test
        void adminCannotListCacheNames() throws Exception {
            cacheInspectionMockMvc.perform(anonymous(HttpMethod.GET, "/cache").with(holding(AuthNaming.AuthRoleNaming.ADMIN)))
                .andExpect(status().isForbidden());
        }

        @Test
        void adminCannotDumpTheSessionsCache() throws Exception {
            cacheInspectionMockMvc
                .perform(anonymous(HttpMethod.GET, "/cache/{name}", "sessions").with(holding(AuthNaming.AuthRoleNaming.ADMIN)))
                .andExpect(status().isForbidden());
        }

        /** An authenticated test user whose only granted authority is {@code authority}. */
        RequestPostProcessor holding(String authority) {
            return user("cache-inspector").authorities(new SimpleGrantedAuthority(authority));
        }
    }

    /** A request to {@code path} under PSAMA's servlet context path, carrying no credentials. */
    static MockHttpServletRequestBuilder anonymous(HttpMethod method, String path, Object... uriVariables) {
        return MockMvcRequestBuilders.request(method, CONTEXT_PATH + path, uriVariables).contextPath(CONTEXT_PATH);
    }

    /** A request to {@code path} bearing a session-bound JWT for the stored user whose role holds the {@code SUPER_ADMIN} privilege. */
    MockHttpServletRequestBuilder asSuperAdmin(HttpMethod method, String path, Object... uriVariables) {
        return anonymous(method, path, uriVariables).header(HttpHeaders.AUTHORIZATION, "Bearer " + superAdminToken);
    }

    Privilege privilege(String name) {
        Privilege privilege = new Privilege();
        privilege.setName(name);
        return privilegeRepository.save(privilege);
    }

    Role role(String name, Privilege privilege) {
        Role role = new Role();
        role.setName(name);
        role.setPrivileges(new HashSet<>(Set.of(privilege)));
        return roleRepository.save(role);
    }

    User userWithRole(String subject, Role role) {
        User user = new User().setSubject(subject).setRoles(new HashSet<>(Set.of(role)));
        user.setEmail(subject + "@example.org");
        return userRepository.save(user);
    }

    AccessRule accessRule(String name) {
        AccessRule rule = new AccessRule();
        rule.setName(name);
        rule.setType(AccessRule.TypeNaming.ALL_EQUALS);
        return accessRuleRepository.save(rule);
    }
}
