DROP TABLE IF EXISTS `query_status`;

CREATE TABLE `query_status` (
    QUERY BINARY(16) NOT NULL,
    GENOMIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    PHENOTYPIC_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    PATIENT_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    QUERY_JSON_STATUS VARCHAR(64) NOT NULL DEFAULT 'Unsent',
    APPROVED DATETIME,
    SITE VARCHAR(64) NOT NULL DEFAULT '',
    PRIMARY KEY (`QUERY`)
);

INSERT INTO `query_status` (QUERY, GENOMIC_STATUS, PHENOTYPIC_STATUS, PATIENT_STATUS, QUERY_JSON_STATUS, APPROVED, SITE)
    VALUES (unhex('33613336393437612D383233312D3131'), 'Uploaded', 'Error', 'Unsent', 'Uploading', '2022-02-22', 'bch');
