name: visualization-service tests
on:
  pull_request:
    paths: ['services/pic-sure-visualization-service/**']
  push:
    branches: [pic_sure_api_mono_repo, pic_sure_api_rewrite, main]
    paths: ['services/pic-sure-visualization-service/**']
defaults:
  run:
    working-directory: services/pic-sure-visualization-service
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '25'
          cache: maven
      - name: Test
        run: mvn -B verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
